# Generated by Django 6.0.3 on 2026-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
